name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Check Node version
        run: node --version

      - name: Check npm version
        run: npm --version