name: Publish npm Package

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        working-directory: ui-utils
        run: npm test


  publish:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Node
        run: node --version

      - name: Configure Nexus authentication
        shell: powershell
        working-directory: ui-utils
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          npm config set registry "http://10.100.102.25:8081/repository/npm-hosted"
          npm config set //10.100.102.25:8081/repository/npm-hosted/:_auth "$( [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${env:NEXUS_USERNAME}:${env:NEXUS_PASSWORD}")) )"
      - name: Publish package
        working-directory: ui-utils
        run: npm publish